import { Flame, Wine, Droplet, Star, UtensilsCrossed, Users } from 'lucide-react';

export interface MenuItem {
  name: string;
  description: string;
  price: string;
  tags: string[];
  image: string;
  slug: string;
  servingSize?: string;
  allergens?: string;
}

export interface MenuCategory {
  id: string;
  name: string;
  icon: any;
  description: string;
  items: MenuItem[];
}

export const menuData: MenuCategory[] = [
  {
    id: 'popular',
    name: 'Populär',
    icon: Star,
    description: 'Våra mest älskade rätter som gästerna återkommer för',
    items: [
      {
        name: 'Ostrullar',
        description: 'Serveras med friterad mozzarella ost i filodeg',
        price: '69 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/Ostrullar.jpg',
        slug: 'ostrullar',
        servingSize: '4 rullar',
        allergens: 'Mjölk, Gluten, Ägg',
      },
      {
        name: 'Chicken Popcorn',
        description: 'Friterad kyckling popcorn med sötsur sås',
        price: '79 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/chicken_popcorn.jpg',
        slug: 'chicken-popcorn',
        servingSize: '1 portion',
        allergens: 'Gluten, Ägg',
      },
      {
        name: 'Arabisk Shawarma',
        description: 'Serveras med pommes och Cream toum',
        price: '149 kr',
        tags: ['Populär'],
        image: '/images/Arabisk_Shawarma.jpg',
        slug: 'arabisk-shawarma',
        servingSize: '1 person',
        allergens: 'Gluten, Vitlök, Mjölk',
      },
      {
        name: 'Kycklingspett',
        description: '2 st kycklingspett med grillade grönsaker',
        price: '169 kr',
        tags: ['Populär'],
        image: '/images/Kycklingspett.jpg',
        slug: 'kycklingspett',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
    ],
  },
  {
    id: 'varma-meza',
    name: 'Varma Meza',
    icon: UtensilsCrossed,
    description: 'Varma förrätter perfekta för delning',
    items: [
      {
        name: 'Ostrullar',
        description: 'Serveras med friterad mozzarella ost i filodeg',
        price: '69 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/Ostrullar.jpg',
        slug: 'ostrullar',
        servingSize: '4 rullar',
        allergens: 'Mjölk, Gluten, Ägg',
      },
      {
        name: 'Kycklingvingar',
        description: 'Grillade små kycklingvingar',
        price: '69 kr',
        tags: ['Förrätt'],
        image: '/images/kycklingvingar.jpg',
        slug: 'kycklingvingar',
        servingSize: '9 st',
        allergens: 'Ingen',
      },
      {
        name: 'Chicken Popcorn',
        description: 'Friterad kyckling popcorn med sötsur sås',
        price: '79 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/chicken_popcorn.jpg',
        slug: 'chicken-popcorn',
        servingSize: '1 portion',
        allergens: 'Gluten, Ägg',
      },
      {
        name: 'Halloumi',
        description: 'Serveras med grillad halloumiost',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/halloumi.jpg',
        slug: 'halloumi',
        servingSize: '4 st',
        allergens: 'Mjölk',
      },
      {
        name: 'Falafel',
        description: 'Krispiga kikärtsbiffar serverade med tahini',
        price: '89 kr',
        tags: ['Förrätt', 'Vegetarisk'],
        image: '/images/falafel.jpg',
        slug: 'falafel',
        servingSize: '6 st',
        allergens: 'Sesam',
      },
      {
        name: 'Lahemagin',
        description: 'Turkisk köttfärs pizza med grönsaker',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/lahemagin.jpg',
        slug: 'lahemagin',
        servingSize: '3 st',
        allergens: 'Gluten',
      },
      {
        name: 'Manakish Zathar',
        description: 'Flatbröd med zathar kryddor och olivolja',
        price: '89 kr',
        tags: ['Förrätt', 'Vegetarisk'],
        image: '/images/manakish_zathar.jpg',
        slug: 'manakish-zathar',
        servingSize: '3 st',
        allergens: 'Gluten, Sesam',
      },
      {
        name: 'Kebbe Trabolesieh',
        description: 'Serveras med friterad nötfärs fyllda bulgurbollar',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/kebbe-trabolesieh.jpg',
        slug: 'kebbe-trabolesieh',
        servingSize: '4 st',
        allergens: 'Gluten',
      },
      {
        name: 'Sambosek Bellahme',
        description: 'Serveras med nötfärspiroger',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/sambosek-bellahme.jpg',
        slug: 'sambosek-bellahme',
        servingSize: '4 st',
        allergens: 'Gluten',
      },
      {
        name: 'Spenatpirog',
        description: 'Krispiga piroger fyllda med spenat',
        price: '89 kr',
        tags: ['Förrätt', 'Vegetarisk'],
        image: '/images/spenatpirog.jpg',
        slug: 'spenatpirog',
        servingSize: '4 st',
        allergens: 'Gluten, Mjölk',
      },
    ],
  },
  {
    id: 'familjebricka',
    name: 'Familjebricka',
    icon: Users,
    description: 'Generösa familjebrickor perfekta för delning',
    items: [
      {
        name: 'Familjebricka för 6 personer – 12 Spett',
        description: 'Serveras med 4 st shish kebab, 4 st kycklingspett, 4 st fläskfilespett och 8 st valfria kalla meza',
        price: '1 049 kr',
        tags: ['För Delning', 'Familj'],
        image: '/images/stor_bricka_12_spett.jpg',
        slug: 'stor-bricka-12-spett',
        servingSize: '6 personer',
        allergens: 'Varierar beroende på meza-val',
      },
      {
        name: 'Familjebricka för 4 personer – 8 Spett',
        description: 'Serveras med 3 st shish kebab, 3 st kycklingspett, 2 st fläskfilespett och 6 st valfria kalla meza',
        price: '849 kr',
        tags: ['För Delning', 'Familj'],
        image: '/images/mellan_bricka_8_spett.jpg',
        slug: 'mellan-bricka-8-spett',
        servingSize: '4 personer',
        allergens: 'Varierar beroende på meza-val',
      },
      {
        name: 'Familjebricka för 2 personer – 4 Spett',
        description: 'Serveras med 2 st shish kebab, 2 st kycklingspett och 4 st valfria kalla meza',
        price: '450 kr',
        tags: ['För Delning'],
        image: '/images/liten_bricka_4_spett.jpg',
        slug: 'liten-bricka-4-spett',
        servingSize: '2 personer',
        allergens: 'Varierar beroende på meza-val',
      },
    ],
  },
  {
    id: 'grillratter',
    name: 'Grillrätter',
    icon: Flame,
    description: 'Färska råvaror grillade till perfektion',
    items: [
      {
        name: 'Kycklingspett',
        description: '2 st kycklingspett med grillade grönsaker',
        price: '169 kr',
        tags: ['Populär'],
        image: '/images/Kycklingspett.jpg',
        slug: 'kycklingspett',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Shish Kebab',
        description: '2 st nöttfärsspett med grillade grönsaker',
        price: '169 kr',
        tags: ['Populär'],
        image: '/images/Shish_Kebab1.jpg',
        slug: 'shish-kebab',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Urfa Kebab',
        description: '2 st nöttfärsspett med grillade grönsaker. Stark',
        price: '169 kr',
        tags: ['Stark'],
        image: '/images/Urfa_Kebab.jpg',
        slug: 'urfa-kebab',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Sahara Mix Spett',
        description: '3 st spett serveras med Fläsk, shish kebab, kyckling och grillade grönsaker',
        price: '209 kr',
        tags: ['För Delning'],
        image: '/images/sahara-mix-spett.jpg',
        slug: 'sahara-mix-spett',
        servingSize: '1-2 personer',
        allergens: 'Ingen',
      },
      {
        name: 'Fläskfilespett',
        description: '2 st fläskfiléspett med grillade grönsaker',
        price: '169 kr',
        tags: [],
        image: '/images/flaskfilespett.jpg',
        slug: 'flaskfilespett',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Lammspett',
        description: '2 st lammspett med grillade grönsaker',
        price: '209 kr',
        tags: [],
        image: '/images/lammspett.jpg',
        slug: 'lammspett',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
    ],
  },
  {
    id: 'cocktails',
    name: 'Signatur Cocktails',
    icon: Wine,
    description: 'Handgjorda cocktails av våra mästerbartenders',
    items: [
      {
        name: 'Sahara Solnedgång',
        description: 'Tequila, passionsfrukt, lime, agave, rökt chilikantering',
        price: '160 kr',
        tags: ['Signatur', 'Stark'],
        image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=2070',
        slug: 'sahara-sunset',
      },
      {
        name: 'Rökig Old Fashioned',
        description: 'Bourbon, lönnsirap, bitters, rökt med hickory-trä',
        price: '180 kr',
        tags: ['Klassisk', 'Rökig'],
        image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?q=80&w=2069',
        slug: 'smoky-old-fashioned',
      },
      {
        name: 'Öken Ros Martini',
        description: 'Gin, rosvatten, fläder, citron, garnerad med rosblad',
        price: '170 kr',
        tags: ['Signatur', 'Blommig'],
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?q=80&w=2086',
        slug: 'desert-rose-martini',
      },
      {
        name: 'Stark Margarita',
        description: 'Tequila, jalapeño, gurka, lime, tajínkant',
        price: '150 kr',
        tags: ['Stark', 'Populär'],
        image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?q=80&w=2069',
        slug: 'spicy-margarita',
      },
      {
        name: 'Förkolnad Ananas Mojito',
        description: 'Vit rom, grillad ananas, mynta, lime, sodavatten',
        price: '140 kr',
        tags: ['Uppfriskande', 'Tropisk'],
        image: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?q=80&w=2074',
        slug: 'charred-pineapple-mojito',
      },
    ],
  },
  {
    id: 'beverages',
    name: 'Färska Juicer & Drycker',
    icon: Droplet,
    description: 'Nypress juicer och uppfriskande alkoholfria drycker',
    items: [
      {
        name: 'Gyllene Gurkmeja Elixir',
        description: 'Färsk gurkmeja, ingefära, apelsin, honung, svartpeppar',
        price: '90 kr',
        tags: ['Hälsosamt', 'Antiinflammatoriskt'],
        image: 'https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?q=80&w=2087',
        slug: 'golden-turmeric-elixir',
      },
      {
        name: 'Bär Explosion',
        description: 'Blandade bär, acai, banan, kokosvatten',
        price: '100 kr',
        tags: ['Hälsosamt', 'Antioxidant'],
        image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?q=80&w=2070',
        slug: 'berry-blast',
      },
      {
        name: 'Grön Detox',
        description: 'Grönkål, spenat, gurka, selleri, grönt äpple, citron, ingefära',
        price: '110 kr',
        tags: ['Detox', 'Hälsosamt'],
        image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?q=80&w=2070',
        slug: 'green-detox',
      },
      {
        name: 'Citrus Soluppgång',
        description: 'Apelsin, grapefrukt, blodapelsin, färsk mynta',
        price: '80 kr',
        tags: ['Vitamin C', 'Uppfriskande'],
        image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=2074',
        slug: 'citrus-sunrise',
      },
      {
        name: 'Mango Lassi',
        description: 'Färsk mango, yoghurt, kardemumma, saffran',
        price: '90 kr',
        tags: ['Krämig', 'Traditionell'],
        image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?q=80&w=2070',
        slug: 'mango-lassi',
      },
    ],
  },
];
