import { Flame, Wine, Droplet, Star, UtensilsCrossed, Users } from 'lucide-react';

export interface MenuItem {
  name: string;
  description: string;
  price: string;
  tags: string[];
  image: string;
  slug: string;
  servingSize?: string;
  allergens?: string;
}

export interface MenuCategory {
  id: string;
  name: string;
  icon: any;
  description: string;
  items: MenuItem[];
}

export const menuData: MenuCategory[] = [
  {
    id: 'popular',
    name: 'Populär',
    icon: Star,
    description: 'Våra mest älskade rätter som gästerna återkommer för',
    items: [
      {
        name: 'Ostrullar',
        description: 'Serveras med friterad mozzarella ost i filodeg',
        price: '69 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/Ostrullar.jpg',
        slug: 'ostrullar',
        servingSize: '4 rullar',
        allergens: 'Mjölk, Gluten, Ägg',
      },
      {
        name: 'Chicken Popcorn',
        description: 'Friterad kyckling popcorn med sötsur sås',
        price: '79 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/chicken_popcorn.jpg',
        slug: 'chicken-popcorn',
        servingSize: '1 portion',
        allergens: 'Gluten, Ägg',
      },
      {
        name: 'Arabisk Shawarma',
        description: 'Serveras med pommes och Cream toum',
        price: '149 kr',
        tags: ['Populär'],
        image: '/images/Arabisk_Shawarma.jpg',
        slug: 'arabisk-shawarma',
        servingSize: '1 person',
        allergens: 'Gluten, Vitlök, Mjölk',
      },
      {
        name: 'Kycklingspett',
        description: '2 st kycklingspett med grillade grönsaker',
        price: '169 kr',
        tags: ['Populär'],
        image: '/images/Kycklingspett.jpg',
        slug: 'kycklingspett',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
    ],
  },
  {
    id: 'varma-meza',
    name: 'Varma Meza',
    icon: UtensilsCrossed,
    description: 'Varma förrätter perfekta för delning',
    items: [
      {
        name: 'Ostrullar',
        description: 'Serveras med friterad mozzarella ost i filodeg',
        price: '69 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/Ostrullar.jpg',
        slug: 'ostrullar',
        servingSize: '4 rullar',
        allergens: 'Mjölk, Gluten, Ägg',
      },
      {
        name: 'Kycklingvingar',
        description: 'Grillade små kycklingvingar',
        price: '69 kr',
        tags: ['Förrätt'],
        image: '/images/kycklingvingar.jpg',
        slug: 'kycklingvingar',
        servingSize: '9 st',
        allergens: 'Ingen',
      },
      {
        name: 'Chicken Popcorn',
        description: 'Friterad kyckling popcorn med sötsur sås',
        price: '79 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/chicken_popcorn.jpg',
        slug: 'chicken-popcorn',
        servingSize: '1 portion',
        allergens: 'Gluten, Ägg',
      },
      {
        name: 'Halloumi',
        description: 'Serveras med grillad halloumiost',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/halloumi.jpg',
        slug: 'halloumi',
        servingSize: '4 st',
        allergens: 'Mjölk',
      },
      {
        name: 'Falafel',
        description: 'Krispiga kikärtsbiffar serverade med tahini',
        price: '89 kr',
        tags: ['Förrätt', 'Vegetarisk'],
        image: '/images/falafel.jpg',
        slug: 'falafel',
        servingSize: '6 st',
        allergens: 'Sesam',
      },
      {
        name: 'Lahemagin',
        description: 'Turkisk köttfärs pizza med grönsaker',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/lahemagin.jpg',
        slug: 'lahemagin',
        servingSize: '3 st',
        allergens: 'Gluten',
      },
      {
        name: 'Manakish Zathar',
        description: 'Flatbröd med zathar kryddor och olivolja',
        price: '89 kr',
        tags: ['Förrätt', 'Vegetarisk'],
        image: '/images/manakish_zathar.jpg',
        slug: 'manakish-zathar',
        servingSize: '3 st',
        allergens: 'Gluten, Sesam',
      },
      {
        name: 'Kebbe Trabolesieh',
        description: 'Serveras med friterad nötfärs fyllda bulgurbollar',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/kebbe-trabolesieh.jpg',
        slug: 'kebbe-trabolesieh',
        servingSize: '4 st',
        allergens: 'Gluten',
      },
      {
        name: 'Sambosek Bellahme',
        description: 'Serveras med nötfärspiroger',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/sambosek-bellahme.jpg',
        slug: 'sambosek-bellahme',
        servingSize: '4 st',
        allergens: 'Gluten',
      },
      {
        name: 'Spenatpirog',
        description: 'Krispiga piroger fyllda med spenat',
        price: '89 kr',
        tags: ['Förrätt', 'Vegetarisk'],
        image: '/images/spenatpirog.jpg',
        slug: 'spenatpirog',
        servingSize: '4 st',
        allergens: 'Gluten, Mjölk',
      },
    ],
  },
  {
    id: 'kall-meza',
    name: 'Kall Meza',
    icon: Droplet,
    description: 'Kalla förrätter och dippar perfekta för delning',
    items: [
      {
        name: 'Hummus',
        description: 'Färsk kikärtsröra med sesampasta.',
        price: '59 kr',
        tags: ['Vegetarisk', 'Förrätt'],
        image: '/images/hummus.avif',
        slug: 'hummus',
        servingSize: '1 portion',
        allergens: 'Sesam',
      },
      {
        name: 'Muhammara',
        description: 'Servera med kryddig paprikaröra.',
        price: '59 kr',
        tags: ['Vegetarisk', 'Förrätt'],
        image: '/images/muhammara.avif',
        slug: 'muhammara',
        servingSize: '1 portion',
        allergens: 'Nötter',
      },
      {
        name: 'Tzatsiki',
        description: 'Yoghurt med vitlök och gurka.',
        price: '59 kr',
        tags: ['Vegetarisk', 'Förrätt'],
        image: '/images/tzatsiki.avif',
        slug: 'tzatsiki',
        servingSize: '1 portion',
        allergens: 'Mjölk',
      },
      {
        name: 'Baba Ganouj',
        description: 'Servera med aubergineröra.',
        price: '59 kr',
        tags: ['Vegetarisk', 'Förrätt'],
        image: '/images/baba-ganouj.avif',
        slug: 'baba-ganouj',
        servingSize: '1 portion',
        allergens: 'Sesam',
      },
      {
        name: 'Tarator',
        description: 'Kycklingröra med yoghurt och sesampasta.',
        price: '59 kr',
        tags: ['Förrätt'],
        image: '/images/tarator.avif',
        slug: 'tarator',
        servingSize: '1 portion',
        allergens: 'Sesam, Mjölk',
      },
      {
        name: 'Warak Inab',
        description: 'Fyllda vinbladsdolmar med ris.',
        price: '79 kr',
        tags: ['Vegetarisk', 'Förrätt'],
        image: '/images/warak-inab.avif',
        slug: 'warak-inab',
        servingSize: '1 portion',
        allergens: 'Ingen',
      },
      {
        name: 'Tabbouleh',
        description: 'Fräsch sallad med bulgur, persilja, tomater och citron, perfekt som förrätt eller tillbehör.',
        price: '59 kr',
        tags: ['Vegetarisk', 'Förrätt'],
        image: '/images/tabbouleh.avif',
        slug: 'tabbouleh',
        servingSize: '1 portion',
        allergens: 'Gluten',
      },
      {
        name: 'Fatosh',
        description: 'Fatosh är en fräsch sallad med grönsaker, bröd och citrondressing.',
        price: '59 kr',
        tags: ['Vegetarisk', 'Förrätt'],
        image: '/images/fatosh.avif',
        slug: 'fatosh',
        servingSize: '1 portion',
        allergens: 'Gluten',
      },
      {
        name: 'Creme Toum',
        description: 'Servera med vitlökskräm.',
        price: '59 kr',
        tags: ['Vegetarisk', 'Förrätt'],
        image: '/images/creme-toum.avif',
        slug: 'creme-toum',
        servingSize: '1 portion',
        allergens: 'Ingen',
      },
    ],
  },
  {
    id: 'familjebricka',
    name: 'Familjebricka',
    icon: Users,
    description: 'Generösa familjebrickor perfekta för delning',
    items: [
      {
        name: 'Familjebricka för 6 personer – 12 Spett',
        description: 'Serveras med 4 st shish kebab, 4 st kycklingspett, 4 st fläskfilespett och 8 st valfria kalla meza',
        price: '1 049 kr',
        tags: ['För Delning', 'Familj'],
        image: '/images/stor_bricka_12_spett.jpg',
        slug: 'stor-bricka-12-spett',
        servingSize: '6 personer',
        allergens: 'Varierar beroende på meza-val',
      },
      {
        name: 'Familjebricka för 4 personer – 8 Spett',
        description: 'Serveras med 3 st shish kebab, 3 st kycklingspett, 2 st fläskfilespett och 6 st valfria kalla meza',
        price: '849 kr',
        tags: ['För Delning', 'Familj'],
        image: '/images/mellan_bricka_8_spett.jpg',
        slug: 'mellan-bricka-8-spett',
        servingSize: '4 personer',
        allergens: 'Varierar beroende på meza-val',
      },
      {
        name: 'Familjebricka för 2 personer – 4 Spett',
        description: 'Serveras med 2 st shish kebab, 2 st kycklingspett och 4 st valfria kalla meza',
        price: '450 kr',
        tags: ['För Delning'],
        image: '/images/liten_bricka_4_spett.jpg',
        slug: 'liten-bricka-4-spett',
        servingSize: '2 personer',
        allergens: 'Varierar beroende på meza-val',
      },
    ],
  },
  {
    id: 'grillratter',
    name: 'Grillrätter',
    icon: Flame,
    description: 'Färska råvaror grillade till perfektion',
    items: [
      {
        name: 'Kycklingspett',
        description: '2 st kycklingspett med grillade grönsaker',
        price: '169 kr',
        tags: ['Populär'],
        image: '/images/Kycklingspett.jpg',
        slug: 'kycklingspett',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Shish Kebab',
        description: '2 st nöttfärsspett med grillade grönsaker',
        price: '169 kr',
        tags: ['Populär'],
        image: '/images/Shish_Kebab1.jpg',
        slug: 'shish-kebab',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Urfa Kebab',
        description: '2 st nöttfärsspett med grillade grönsaker. Stark',
        price: '169 kr',
        tags: ['Stark'],
        image: '/images/Urfa_Kebab.jpg',
        slug: 'urfa-kebab',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Sahara Mix Spett',
        description: '3 st spett serveras med Fläsk, shish kebab, kyckling och grillade grönsaker',
        price: '209 kr',
        tags: ['För Delning'],
        image: '/images/sahara-mix-spett.jpg',
        slug: 'sahara-mix-spett',
        servingSize: '1-2 personer',
        allergens: 'Ingen',
      },
      {
        name: 'Fläskfilespett',
        description: '2 st fläskfiléspett med grillade grönsaker',
        price: '169 kr',
        tags: [],
        image: '/images/flaskfilespett.jpg',
        slug: 'flaskfilespett',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Lammspett',
        description: '2 st lammspett med grillade grönsaker',
        price: '209 kr',
        tags: [],
        image: '/images/lammspett.jpg',
        slug: 'lammspett',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Falafeltallrik',
        description: '8 st falafelbollar med sallad.',
        price: '129 kr',
        tags: ['Vegetarisk'],
        image: '/images/falafeltallrik.avif',
        slug: 'falafeltallrik',
        servingSize: '1 person',
        allergens: 'Sesam, Gluten',
      },
      {
        name: 'Crispy Chicken',
        description: 'Krispig kyckling serverad med pommes och sallad.',
        price: '169 kr',
        tags: ['Populär'],
        image: '/images/crispy-chicken.avif',
        slug: 'crispy-chicken',
        servingSize: '1 person',
        allergens: 'Gluten, Ägg',
      },
    ],
  },
  {
    id: 'milkshake',
    name: 'Milkshake',
    icon: Wine,
    description: 'Krämiga och söta milkshakes gjorda på färska ingredienser',
    items: [
      {
        name: 'Jordgubb Milkshake',
        description: 'En krämig och söt dryck med färska jordgubbar och mjölk, perfekt för sommaren.',
        price: '69 kr',
        tags: ['Populär'],
        image: '/images/jordgubb-milkshake.avif',
        slug: 'jordgubb-milkshake',
        servingSize: '1 glas',
        allergens: 'Mjölk',
      },
      {
        name: 'Milkshake Oreo',
        description: 'En krämig och söt dryck med smak av chokladkakor och vaniljglass.',
        price: '69 kr',
        tags: ['Populär'],
        image: '/images/milkshake-oreo.avif',
        slug: 'milkshake-oreo',
        servingSize: '1 glas',
        allergens: 'Mjölk, Gluten',
      },
      {
        name: 'Lotus Milkshake',
        description: 'En krämig milkshake med den härliga smaken av Lotus Biscoff.',
        price: '69 kr',
        tags: [],
        image: '/images/lotus-milkshake.avif',
        slug: 'lotus-milkshake',
        servingSize: '1 glas',
        allergens: 'Mjölk, Gluten',
      },
    ],
  },
  {
    id: 'mocktails',
    name: 'Mocktails',
    icon: Droplet,
    description: 'Uppfriskande alkoholfria cocktails gjorda på färska frukter',
    items: [
      {
        name: 'Ananas Cocktail',
        description: 'Fräsch och tropisk mocktail med färsk ananas och citrus.',
        price: '89 kr',
        tags: ['Uppfriskande'],
        image: '/images/ananas-cocktail.avif',
        slug: 'ananas-cocktail',
        servingSize: '1 glas',
        allergens: 'Ingen',
      },
      {
        name: 'Blue Ocean Cocktail',
        description: 'Exotisk mocktail med blå curaçaosmak och tropiska frukter.',
        price: '89 kr',
        tags: ['Populär'],
        image: '/images/blue-ocean-cocktail.avif',
        slug: 'blue-ocean-cocktail',
        servingSize: '1 glas',
        allergens: 'Ingen',
      },
      {
        name: 'Citron & Mint Cocktail',
        description: 'Uppfriskande mocktail med färsk citron och mynta.',
        price: '89 kr',
        tags: ['Uppfriskande'],
        image: '/images/citron-mint-cocktail.avif',
        slug: 'citron-mint-cocktail',
        servingSize: '1 glas',
        allergens: 'Ingen',
      },
      {
        name: 'Mango Cocktail',
        description: 'Söt och tropisk mocktail med färsk mango.',
        price: '89 kr',
        tags: ['Tropisk'],
        image: '/images/mango-cocktail.avif',
        slug: 'mango-cocktail',
        servingSize: '1 glas',
        allergens: 'Ingen',
      },
      {
        name: 'Passion Cocktail',
        description: 'Exotisk mocktail med passionsfrukt och tropiska smaker.',
        price: '89 kr',
        tags: ['Tropisk'],
        image: '/images/passion-cocktail.avif',
        slug: 'passion-cocktail',
        servingSize: '1 glas',
        allergens: 'Ingen',
      },
    ],
  },
];
