import { Award, ChefHat, Flame, Wine, Droplet, Star, UtensilsCrossed, Users } from 'lucide-react';

export interface MenuItem {
  name: string;
  description: string;
  price: string;
  tags: string[];
  image: string;
  slug: string;
  prepTime?: string;
  servingSize?: string;
  allergens?: string;
}

export interface MenuCategory {
  id: string;
  name: string;
  icon: any;
  description: string;
  items: MenuItem[];
}

export const menuData: MenuCategory[] = [
  {
    id: 'popular',
    name: 'Populär',
    icon: Star,
    description: 'Våra mest älskade rätter som gästerna återkommer för',
    items: [
      {
        name: 'Ostrullar',
        description: 'Serveras med friterad mozzarella ost i filodeg',
        price: '69 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/Ostrullar.jpg',
        slug: 'ostrullar',
        prepTime: '8-10 min',
        servingSize: '4 rullar',
        allergens: 'Mjölk, Gluten, Ägg',
      },
      {
        name: 'Chicken Popcorn',
        description: 'Friterad kyckling popcorn med sötsur sås',
        price: '79 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/chicken_popcorn.jpg',
        slug: 'chicken-popcorn',
        prepTime: '8-10 min',
        servingSize: '1 portion',
        allergens: 'Gluten, Ägg',
      },
      {
        name: 'Arabisk Shawarma',
        description: 'Serveras med pommes och Cream toum',
        price: '149 kr',
        tags: ['Populär'],
        image: '/images/Arabisk_Shawarma.jpg',
        slug: 'arabisk-shawarma',
        prepTime: '15-20 min',
        servingSize: '1 person',
        allergens: 'Gluten, Vitlök, Mjölk',
      },
      {
        name: 'Kycklingspett',
        description: '2 st kycklingspett med grillade grönsaker',
        price: '169 kr',
        tags: ['Populär'],
        image: '/images/Kycklingspett.jpg',
        slug: 'kycklingspett',
        prepTime: '15-20 min',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
    ],
  },
  {
    id: 'varma-meza',
    name: 'Varma Meza',
    icon: UtensilsCrossed,
    description: 'Varma förrätter perfekta för delning',
    items: [
      {
        name: 'Ostrullar',
        description: 'Serveras med friterad mozzarella ost i filodeg',
        price: '69 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/Ostrullar.jpg',
        slug: 'ostrullar',
        prepTime: '8-10 min',
        servingSize: '4 rullar',
        allergens: 'Mjölk, Gluten, Ägg',
      },
      {
        name: 'Kycklingvingar',
        description: 'Grillade små kycklingvingar',
        price: '69 kr',
        tags: ['Förrätt'],
        image: '/images/kycklingvingar.jpg',
        slug: 'kycklingvingar',
        prepTime: '10-12 min',
        servingSize: '9 st',
        allergens: 'Ingen',
      },
      {
        name: 'Chicken Popcorn',
        description: 'Friterad kyckling popcorn med sötsur sås',
        price: '79 kr',
        tags: ['Populär', 'Förrätt'],
        image: '/images/chicken_popcorn.jpg',
        slug: 'chicken-popcorn',
        prepTime: '5-10 min',
        servingSize: '1 portion',
        allergens: 'Gluten, Ägg',
      },
      {
        name: 'Halloumi',
        description: 'Serveras med grillad halloumiost',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/halloumi.jpg',
        slug: 'halloumi',
        prepTime: '10-15 min',
        servingSize: '4 st',
        allergens: 'Mjölk',
      },
      {
        name: 'Falafel',
        description: 'Krispiga kikärtsbiffar serverade med tahini',
        price: '89 kr',
        tags: ['Förrätt', 'Vegetarisk'],
        image: '/images/falafel.jpg',
        slug: 'falafel',
        prepTime: '8-10 min',
        servingSize: '6 st',
        allergens: 'Sesam',
      },
      {
        name: 'Lahemagin',
        description: 'Turkisk köttfärs pizza med grönsaker',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/lahemagin.jpg',
        slug: 'lahemagin',
        prepTime: '10-15 min',
        servingSize: '3 st',
        allergens: 'Gluten',
      },
      {
        name: 'Manakish Zathar',
        description: 'Flatbröd med zathar kryddor och olivolja',
        price: '89 kr',
        tags: ['Förrätt', 'Vegetarisk'],
        image: '/images/manakish_zathar.jpg',
        slug: 'manakish-zathar',
        prepTime: '10-15 min',
        servingSize: '3 st',
        allergens: 'Gluten, Sesam',
      },
      {
        name: 'Kebbe Trabolesieh',
        description: 'Serveras med friterad nötfärs fyllda bulgurbollar',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/kebbe-trabolesieh.jpg',
        slug: 'kebbe-trabolesieh',
        prepTime: '10-15 min',
        servingSize: '4 st',
        allergens: 'Gluten',
      },
      {
        name: 'Sambosek Bellahme',
        description: 'Serveras med nötfärspiroger',
        price: '89 kr',
        tags: ['Förrätt'],
        image: '/images/sambosek-bellahme.jpg',
        slug: 'sambosek-bellahme',
        prepTime: '10-15 min',
        servingSize: '4 st',
        allergens: 'Gluten',
      },
      {
        name: 'Spenatpirog',
        description: 'Krispiga piroger fyllda med spenat',
        price: '89 kr',
        tags: ['Förrätt', 'Vegetarisk'],
        image: '/images/spenatpirog.jpg',
        slug: 'spenatpirog',
        prepTime: '8-10 min',
        servingSize: '4 st',
        allergens: 'Gluten, Mjölk',
      },
    ],
  },
  {
    id: 'familjebricka',
    name: 'Familjebricka',
    icon: Users,
    description: 'Generösa familjebrickor perfekta för delning',
    items: [
      {
        name: 'Stor Bricka 12 Spett',
        description: 'Serveras med 4 st shish kebab, 4 st kycklingspett, 4 st fläskfilespett och 8 st valfria kalla meza',
        price: '1 049 kr',
        tags: ['För Delning', 'Familj'],
        image: '/images/stor_bricka_12_spett.jpg',
        slug: 'stor-bricka-12-spett',
        prepTime: '25-30 min',
        servingSize: '4-6 personer',
        allergens: 'Varierar beroende på meza-val',
      },
      {
        name: 'Mellan Bricka 8 Spett',
        description: 'Serveras med 3 st shish kebab, 3 st kycklingspett, 2 st fläskfilespett och 6 st valfria kalla meza',
        price: '849 kr',
        tags: ['För Delning', 'Familj'],
        image: '/images/mellan_bricka_8_spett.jpg',
        slug: 'mellan-bricka-8-spett',
        prepTime: '20-25 min',
        servingSize: '3-4 personer',
        allergens: 'Varierar beroende på meza-val',
      },
      {
        name: 'Liten Bricka 4 Spett',
        description: 'Serveras med 2 st shish kebab, 2 st kycklingspett och 4 st valfria kalla meza',
        price: '450 kr',
        tags: ['För Delning'],
        image: '/images/liten_bricka_4_spett.jpg',
        slug: 'liten-bricka-4-spett',
        prepTime: '15-20 min',
        servingSize: '2-3 personer',
        allergens: 'Varierar beroende på meza-val',
      },
    ],
  },
  {
    id: 'grillratter',
    name: 'Grillrätter',
    icon: Flame,
    description: 'Färska råvaror grillade till perfektion',
    items: [
      {
        name: 'Kycklingspett',
        description: '2 st kycklingspett med grillade grönsaker',
        price: '169 kr',
        tags: ['Populär'],
        image: '/images/Kycklingspett.jpg',
        slug: 'kycklingspett',
        prepTime: '15-20 min',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Shish Kebab',
        description: '2 st nöttfärsspett med grillade grönsaker',
        price: '169 kr',
        tags: ['Populär'],
        image: '/images/Shish_Kebab1.jpg',
        slug: 'shish-kebab',
        prepTime: '15-20 min',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Urfa Kebab',
        description: '2 st nöttfärsspett med grillade grönsaker. Stark',
        price: '169 kr',
        tags: ['Stark'],
        image: '/images/Urfa_Kebab.jpg',
        slug: 'urfa-kebab',
        prepTime: '15-18 min',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Sahara Mix Spett',
        description: '3 st spett serveras med Fläsk, shish kebab, kyckling och grillade grönsaker',
        price: '209 kr',
        tags: ['För Delning'],
        image: '/images/sahara-mix-spett.jpg',
        slug: 'sahara-mix-spett',
        prepTime: '15-25 min',
        servingSize: '1-2 personer',
        allergens: 'Ingen',
      },
      {
        name: 'Fläskfilespett',
        description: '2 st fläskfiléspett med grillade grönsaker',
        price: '169 kr',
        tags: [],
        image: '/images/flaskfilespett.jpg',
        slug: 'flaskfilespett',
        prepTime: '15-25 min',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Lammspett',
        description: '2 st lammspett med grillade grönsaker',
        price: '209 kr',
        tags: [],
        image: '/images/lammspett.jpg',
        slug: 'lammspett',
        prepTime: '15-25 min',
        servingSize: '1 person',
        allergens: 'Ingen',
      },
      {
        name: 'Wagyu Tomahawk Biff',
        description: 'Premium 900g entrecôte med ben, grillad till perfektion med örtsmör och säsongens grönsaker',
        price: '890 kr',
        tags: ['Kockens Special', 'Premium'],
        image: 'https://images.unsplash.com/photo-1558030006-450675393462?q=80&w=2031',
        slug: 'wagyu-tomahawk-steak',
        prepTime: '25-30 min',
        servingSize: '1-2 personer',
        allergens: 'Mjölk (smör)',
      },
      {
        name: 'Mixad Grill Tallrik',
        description: 'Lammkotletter, oxfilé, kycklingspett, merguez korv och grillade grönsaker',
        price: '680 kr',
        tags: ['Populär', 'För Delning'],
        image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=2787',
        slug: 'mixed-grill-platter',
      },
      {
        name: 'Entrecôte Premium',
        description: '450g torrmognad entrecôte med tryffelpotatis och rödvinsreduktion',
        price: '540 kr',
        tags: ['Premium'],
        image: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?q=80&w=2070',
        slug: 'ribeye-premium-cut',
      },
      {
        name: 'Filet Mignon',
        description: '225g innerfilé med béarnaisesås och sparris',
        price: '620 kr',
        tags: ['Premium', 'Mör'],
        image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?q=80&w=2080',
        slug: 'filet-mignon',
      },
    ],
  },
  {
    id: 'specialties',
    name: 'Husets Specialiteter',
    icon: ChefHat,
    description: 'Unika kreationer skapade av våra mästerkockar',
    items: [
      {
        name: 'BBQ Revbensspjäll',
        description: 'Långkokt revben med signatur BBQ-glasyr, coleslaw och majsbröd',
        price: '380 kr',
        tags: ['Populär', 'Långkokt'],
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=2069',
        slug: 'bbq-baby-back-ribs',
      },
      {
        name: 'Grillad Lammracks',
        description: 'Nyzeeländskt lamm med rosmarinsky, rostade grönsaker och mintpesto',
        price: '520 kr',
        tags: ['Kockens Special'],
        image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?q=80&w=2070',
        slug: 'grilled-lamb-rack',
      },
      {
        name: 'Spatchcock Kyckling',
        description: 'Hel uppklippt kyckling med Provence-örter och vitlöksconfit',
        price: '360 kr',
        tags: ['För Delning', 'Populär'],
        image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?q=80&w=2787',
        slug: 'spatchcock-chicken',
      },
    ],
  },
  {
    id: 'smokehouse',
    name: 'Rökhuset',
    icon: Flame,
    description: 'Långsamt rökt kött med autentiska smaker',
    items: [
      {
        name: 'Rökt Brisket',
        description: '12-timmars rökt oxbringa med BBQ bönor, pickles och majsbröd',
        price: '360 kr',
        tags: ['Rökt 12h', 'Populär'],
        image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?q=80&w=2787',
        slug: 'smoked-brisket',
      },
      {
        name: 'Pulled Pork Tallrik',
        description: 'Långrökt pulled pork med tre hemgjorda såser och coleslaw',
        price: '320 kr',
        tags: ['Populär', 'Mört'],
        image: 'https://images.unsplash.com/photo-1558030006-450675393462?q=80&w=2031',
        slug: 'pulled-pork-platter',
      },
      {
        name: 'Rökt Kycklingvingar',
        description: 'Hickory-rökt vingar med buffalo eller honey BBQ sås (12 st)',
        price: '240 kr',
        tags: ['Förrätt', 'Stark'],
        image: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?q=80&w=2835',
        slug: 'smoked-chicken-wings',
      },
      {
        name: 'Texas Tri-Tip',
        description: '400g rökt tri-tip med jalapeño mac & cheese och bourbonglasyr',
        price: '440 kr',
        tags: ['Stark', 'Populär'],
        image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=2080',
        slug: 'texas-tri-tip',
      },
    ],
  },
  {
    id: 'cocktails',
    name: 'Signatur Cocktails',
    icon: Wine,
    description: 'Handgjorda cocktails av våra mästerbartenders',
    items: [
      {
        name: 'Sahara Solnedgång',
        description: 'Tequila, passionsfrukt, lime, agave, rökt chilikantering',
        price: '160 kr',
        tags: ['Signatur', 'Stark'],
        image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=2070',
        slug: 'sahara-sunset',
      },
      {
        name: 'Rökig Old Fashioned',
        description: 'Bourbon, lönnsirap, bitters, rökt med hickory-trä',
        price: '180 kr',
        tags: ['Klassisk', 'Rökig'],
        image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?q=80&w=2069',
        slug: 'smoky-old-fashioned',
      },
      {
        name: 'Öken Ros Martini',
        description: 'Gin, rosvatten, fläder, citron, garnerad med rosblad',
        price: '170 kr',
        tags: ['Signatur', 'Blommig'],
        image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?q=80&w=2086',
        slug: 'desert-rose-martini',
      },
      {
        name: 'Stark Margarita',
        description: 'Tequila, jalapeño, gurka, lime, tajínkant',
        price: '150 kr',
        tags: ['Stark', 'Populär'],
        image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?q=80&w=2069',
        slug: 'spicy-margarita',
      },
      {
        name: 'Förkolnad Ananas Mojito',
        description: 'Vit rom, grillad ananas, mynta, lime, sodavatten',
        price: '140 kr',
        tags: ['Uppfriskande', 'Tropisk'],
        image: 'https://images.unsplash.com/photo-1546171753-97d7676e4602?q=80&w=2074',
        slug: 'charred-pineapple-mojito',
      },
    ],
  },
  {
    id: 'beverages',
    name: 'Färska Juicer & Drycker',
    icon: Droplet,
    description: 'Nypress juicer och uppfriskande alkoholfria drycker',
    items: [
      {
        name: 'Vattenmelon Mynta Cooler',
        description: 'Färsk vattenmelon, mynta, lime, mousserande vatten',
        price: '80 kr',
        tags: ['Uppfriskande', 'Populär'],
        image: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f4d?q=80&w=2070',
        slug: 'watermelon-mint-cooler',
      },
      {
        name: 'Gyllene Gurkmeja Elixir',
        description: 'Färsk gurkmeja, ingefära, apelsin, honung, svartpeppar',
        price: '90 kr',
        tags: ['Hälsosamt', 'Antiinflammatoriskt'],
        image: 'https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?q=80&w=2087',
        slug: 'golden-turmeric-elixir',
      },
      {
        name: 'Bär Explosion',
        description: 'Blandade bär, acai, banan, kokosvatten',
        price: '100 kr',
        tags: ['Hälsosamt', 'Antioxidant'],
        image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?q=80&w=2070',
        slug: 'berry-blast',
      },
      {
        name: 'Grön Detox',
        description: 'Grönkål, spenat, gurka, selleri, grönt äpple, citron, ingefära',
        price: '110 kr',
        tags: ['Detox', 'Hälsosamt'],
        image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?q=80&w=2070',
        slug: 'green-detox',
      },
      {
        name: 'Citrus Soluppgång',
        description: 'Apelsin, grapefrukt, blodapelsin, färsk mynta',
        price: '80 kr',
        tags: ['Vitamin C', 'Uppfriskande'],
        image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=2074',
        slug: 'citrus-sunrise',
      },
      {
        name: 'Mango Lassi',
        description: 'Färsk mango, yoghurt, kardemumma, saffran',
        price: '90 kr',
        tags: ['Krämig', 'Traditionell'],
        image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?q=80&w=2070',
        slug: 'mango-lassi',
      },
    ],
  },
];
